[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = "0.6.0"
piston_window = "0.124.0"
rand = "0.8.5"
rodio = "0.16.0"
